First commit
penny95/challenge-two-part-2 pull request #1
Opened 2019-11-18 19:45 UTC by penny95

Java script program that creates an object where keys are number from 1 to 15 and the values are their squares @dennisja

2019-11-19 08:34 UTC, dennisja requested changes

2019-11-19 08:34 UTC, dennisja commented on Obj.js
> +      [number]:[number]*[number],
This doesn't work. Computed properties should only be used for object keys i.e the correct version of this line would be 
```js
var obj = {
// use [] in the key because we want to use the value of the variable number as the key
[number]: number * number
}
```

2019-11-19 08:34 UTC, dennisja commented on Obj.js
> +      [number]:[number]*[number],
JavaScript has a new exponentiation operator which we can use to find the square of a number i.e
```js
// instead of
[number]: number * number

// we can use the exponentiation operator instead
[number]: number ** 2

// or even use the pow method from Math
[number]: Math.pow(number, 2)
```
I would recommend you use the exponentiation operator

2019-11-19 08:34 UTC, dennisja commented on Obj.js
> +for(number=0; number<=15; number++)
Your logic is still wrong so let's look at what your program does.
You create a variable called number to keep track of the numbers. Loop through numbers from 0 to 15 and for each number you are creating a new object containing that number as a key and its square as a value.

But what we want is, create one object that contains all the numbers as keys and there squares as values. So what you should do instead. Create the object outside the loop
e.g
```js
var numbersObject = {}
```

And loop through the numbers from 0 to 15 adding the number as a key and their square as a value in the for loop.
JavaScript gives you a way of adding key value pairs to an already created object e.g
```js
// we will be using dj as the key nut its stored in the myKey variable
var myKey = "dj"

// we will be using 13 as the value to the key dj but its stored in myValue variable
var myValue = 13

// we create an empty object
var myObject = {}

// we add the key dj whose value is 13 to myObject
myObject[myKey] = myValue

console.log(myObject) // logs out { dj: 13 }
```

2019-11-20 10:28 UTC, penny95 commented on Obj.js
> +      [number]:[number]*[number],
Done

2019-11-20 10:28 UTC, penny95 commented on Obj.js
> +      [number]:[number]*[number],
Done

2019-11-20 10:28 UTC, penny95 commented on Obj.js
> +      [number]:[number]*[number],
Changed to exponential operator

2019-11-20 10:29 UTC, penny95 commented on Obj.js
> +for(number=0; number<=15; number++)
Done that. It now outputs one object for all values

2019-11-20 10:30 UTC, merged